package com.rentspotter.RentSpotter.RentalHistoryAnalytic.service.impl;

import com.rentspotter.RentSpotter.RentalHistoryAnalytic.model.RentalRecord;
import com.rentspotter.RentSpotter.RentalHistoryAnalytic.service.DocumentService;
import com.rentspotter.RentSpotter.RentalHistoryAnalytic.service.HistoryService;
import com.rentspotter.RentSpotter.RentalHistoryAnalytic.service.RatingService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class DocumentServiceImpl implements DocumentService {

    @Autowired
    private HistoryService historyService;
    @Autowired
    private RatingService ratingService;

    @Override
    public String generateReferenceLetter(String recordId) {
        RentalRecord record = historyService.getRecordById(recordId);
        double score = ratingService.getTrustScore(record.getTenantId());
        StringBuilder letter = new StringBuilder();
        letter.append("=== OFFICIAL REFERENCE LETTER ===\n");
        letter.append("Tenant: ").append(record.getTenantId()).append("\n");
        letter.append("Property: ").append(record.getPropertyName()).append("\n");
        if (score >= 4.5) {
            letter.append("STATUS: GOLD STAR TENANT (Highly Recommended)\n");
            letter.append("This tenant has an exceptional trust score of ").append(score).append(".\n");
        } else if (score >= 3.0) {
            letter.append("STATUS: GOOD STANDING\n");
        } else {
            letter.append("STATUS: PROBATIONARY\n");
            letter.append("Note: This tenant has a lower than average trust score.\n");
        }
        letter.append("Generated by RentSpotter.\n");
        return letter.toString();
    }
}
